SECTION "Tiles", ROM0

tile_player_top::
    DB $18,$18, $00,$3C, $3C,$66, $7E,$81
    DB $7E,$99, $00,$7E, $81,$7E, $81,$7E

tile_player_bottom::
    DB $00,$7E, $00,$7E, $00,$66, $00,$66
    DB $00,$66, $66,$66, $E7,$E7, $00,$00

tile_bg_blank::
    DB $00,$00,$00,$00,$00,$00,$00,$00
    DB $00,$00,$00,$00,$00,$00,$00,$00

TilesTotal::
TilesTotalTLE0::
   ; MUROPRUEBA.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : Each tile separate.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 16 x 16
;   Tiles                : 0 to 1
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2


; Start of tile array.
muroprueba::
muropruebaTLE0::
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
muropruebaTLE1::
DB $FF,$00,$FF,$00,$FF,$00,$FF,$00
DB $FF,$00,$FF,$00,$FF,$00,$FF,$00

; End of MUROPRUEBA.Z80
TilesTotalEnd::

    ; End of TILES_TOTAL.Z80
